name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on:
    milestone:
        types: [opened]

jobs:
    milestone-workflow:
        runs-on: ubuntu-latest
        steps: 
            - name: Echo a message
              run: echo "${{ github.actor }} opened a milestone"