name: Action on edited Milestone

run-name: ${{ github.actor }} edited a milestone

on:
    milestone:
        types: [edited]

jobs:
    milestone-workflow:
        runs-on: ubuntu-latest
        steps: 
            - name: Echo a message
              run: echo "${{ github.actor }} edited a milestone"