name: Action on deleted Milestone

run-name: ${{ github.actor }} deleted a milestone

on:
    milestone:
        types: [deleted]

jobs:
    milestone-workflow:
        runs-on: ubuntu-latest
        steps: 
            - name: Echo a message
              run: echo "${{ github.actor }} deleted a milestone"