name: Scheduled job

run-name: ${{ github.actor }} closed a milestone

on:
    schedule:
        - cron: '5 * * * *'

jobs:
    milestone-workflow:
        runs-on: ubuntu-latest
        steps: 
            - name: Create an issue
              run: gh issue create -t 'This is a test '$(date +%Y%m%d)  -b 'This is the body of the issue' -m 'Here is a new milestone'