name: Scheduled job

run-name: ${{ github.actor }} scheduled a job

on:
    schedule:
        - cron: '* 4 * * *'

jobs:
    milestone-workflow:
        runs-on: ubuntu-latest
        steps: 
            - name: Create an issue
              run: gh issue create -t 'This is a test '$(date +Y%m%d%H%M%S)  -b 'This is the body of the issue' -m 'Here is a new milestone'
        env:
            GH_TOKEN: ${{ github.token }}
