name: Wiki to Docs Sync

run-name: ${{ github.actor }} updated wiki - syncing to docs directory

on:
  gollum:

permissions:
  contents: write

jobs:
  sync-wiki-to-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Sync wiki pages to docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/sync-wiki-to-docs.js

      - name: Commit synced documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add docs/
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📚 Sync wiki changes to docs directory

Wiki pages updated:
$(echo '${{ toJson(github.event.pages) }}' | jq -r '.[].page_name' | sed 's/^/- /')

🤖 Auto-synced from wiki via gollum trigger"
            
            git push
          fi